version: '3'
services:
  web:
    build: ./web
    command: ["npm", "start"]
    volumes:
      - ./web/:/app
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build: ./api
    command: ./bin/start.sh
    volumes:
      - ruby-2.6-gems:/usr/local/bundle
      - ./api/:/app
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    hostname: db
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password

volumes:
  ruby-2.6-gems:
    # uncomment 2 lines below if you have global volume with gems
    external: true
    name: ruby-2.6-gems
  db-data:
